# Generated by Django 4.2.7 on 2023-11-26 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evotar', '0004_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('candidatos', models.ManyToManyField(related_name='eleicoes', to='evotar.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato_escolhido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evotar.candidato')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evotar.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
