# Generated by Django 4.2.7 on 2023-11-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evotar', '0005_eleicao_voto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='name',
            new_name='nome',
        ),
    ]
