# Generated by Django 4.2.7 on 2023-11-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evotar', '0006_rename_name_candidato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
