# Generated by Django 4.2.7 on 2023-11-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('evotar', '0009_alter_eleitor_groups_alter_eleitor_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='eleitor_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='eleitor_user_permissions', to='auth.permission'),
        ),
    ]
